set(SQLITE_VEC_ROOT "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/sqlite-vec")
set(SQLITE_VEC_GENERATED_DIR "${CMAKE_CURRENT_BINARY_DIR}/generated/sqlite-vec")

if(NOT EXISTS "${SQLITE_VEC_ROOT}/sqlite-vec.c")
    message(FATAL_ERROR "sqlite-vec source not found at ${SQLITE_VEC_ROOT}. Did you init submodules?")
endif()

file(MAKE_DIRECTORY "${SQLITE_VEC_GENERATED_DIR}")

file(READ "${SQLITE_VEC_ROOT}/VERSION" SQLITE_VEC_VERSION_RAW)
string(STRIP "${SQLITE_VEC_VERSION_RAW}" SQLITE_VEC_VERSION)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)" SQLITE_VEC_VERSION_MATCH "${SQLITE_VEC_VERSION}")
if(NOT SQLITE_VEC_VERSION_MATCH)
    message(FATAL_ERROR "Unable to parse sqlite-vec version from ${SQLITE_VEC_ROOT}/VERSION: ${SQLITE_VEC_VERSION}")
endif()

set(SQLITE_VEC_VERSION_MAJOR "${CMAKE_MATCH_1}")
set(SQLITE_VEC_VERSION_MINOR "${CMAKE_MATCH_2}")
set(SQLITE_VEC_VERSION_PATCH "${CMAKE_MATCH_3}")

if(DEFINED ENV{SOURCE_DATE_EPOCH})
    string(TIMESTAMP SQLITE_VEC_DATE "%Y-%m-%dT%H:%M:%SZ" UTC)
else()
    string(TIMESTAMP SQLITE_VEC_DATE "%Y-%m-%dT%H:%M:%SZ" UTC)
endif()

set(SQLITE_VEC_SOURCE "local")

file(READ "${SQLITE_VEC_ROOT}/sqlite-vec.h.tmpl" SQLITE_VEC_HEADER_TEMPLATE)
string(REPLACE "\${VERSION}" "${SQLITE_VEC_VERSION}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_TEMPLATE}")
string(REPLACE "\${DATE}" "${SQLITE_VEC_DATE}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_CONTENT}")
string(REPLACE "\${SOURCE}" "${SQLITE_VEC_SOURCE}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_CONTENT}")
string(REPLACE "\${VERSION_MAJOR}" "${SQLITE_VEC_VERSION_MAJOR}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_CONTENT}")
string(REPLACE "\${VERSION_MINOR}" "${SQLITE_VEC_VERSION_MINOR}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_CONTENT}")
string(REPLACE "\${VERSION_PATCH}" "${SQLITE_VEC_VERSION_PATCH}" SQLITE_VEC_HEADER_CONTENT "${SQLITE_VEC_HEADER_CONTENT}")

file(WRITE "${SQLITE_VEC_GENERATED_DIR}/sqlite-vec.h" "${SQLITE_VEC_HEADER_CONTENT}")

add_library(sqlite_vec STATIC
    "${SQLITE_VEC_ROOT}/sqlite-vec.c"
)

target_link_libraries(sqlite_vec PUBLIC unofficial::sqlite3::sqlite3)

target_include_directories(sqlite_vec
    PUBLIC
        "${SQLITE_VEC_GENERATED_DIR}"
    PRIVATE
        "${SQLITE_VEC_ROOT}"
)

target_compile_definitions(sqlite_vec
    PUBLIC
        SQLITE_CORE
        SQLITE_VEC_STATIC
)

if(MSVC)
    target_compile_definitions(sqlite_vec PRIVATE _CRT_SECURE_NO_WARNINGS)
endif()
